### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by yunzqq** [gcambara/cape#1]
Is there TensorFlow implementation?

**Comment by gcambara** [comment]
Hi! I'm afraid not, as I'm not experienced in TF programming. Feel free to reuse my code if you need to do a port to TF, or reach out if you have any questions.

**Comment by yunzqq** [comment]
> Hi! I'm afraid not, as I'm not experienced in TF programming. Feel free to reuse my code if you need to do a port to TF, or reach out if you have any questions.

Thank you very much for your response!
